### ISSUE TITLE
Панель поиска заходит под иконку поиска

### ISSUE THREAD

**Issue by mutantcornholio** [vas3k/player.vas3k.ru#1]
Собственно, заходит, и, поэтому, мы не видим последние символы длинного поискового ввода.

**Comment by vas3k** [comment]
Ок

**Comment by mutantcornholio** [comment]
Хм... может.. убрать правые радиусы у поля и левые - у иконки. Кажется, так будет симпатичнее. Хотя из меня дизайнер..

**Comment by vas3k** [comment]
А у меня как?

**Comment by mutantcornholio** [comment]
http://dl.getdropbox.com/u/1880889/2011-01-29-005338_1920x1080_scrot.png
Лиса, кэшик чистил

**Comment by vas3k** [comment]
А, ты бедный пользователь убогого браузера, который в 2011 году не умеет border-radius. Да, у меня как раз в планах вами заняться.

**Comment by mutantcornholio** [comment]
в геко до сих пор префиксы?

**Comment by vas3k** [comment]
Ага. Даже в 4.0pre

**Comment by mutantcornholio** [comment]
ты... зачем сделал фон полей белым, а текст чёрным - не сделал?

**Comment by mutantcornholio** [comment]
У меня как-то маленький поиск по пикселям не совпадает

**Comment by mutantcornholio** [comment]
теперь и большой(

**Comment by mutantcornholio** [comment]
зато текст - чёрный ^_^ я тебя люблю
