### ISSUE TITLE
Постоянно слетает авторизация last.fm 

### ISSUE THREAD

**Issue by mutantcornholio** [vas3k/player.vas3k.ru#10]
Есть ли способ проверить, слетела она, или нет?
Если есть, может, сделать опцию, чтоб она заново запускалась?

**Comment by vas3k** [comment]
Чето поменял, посмотрим.

**Comment by vas3k** [comment]
Вроде бы со второго раза починилось. Пару дней наблюдаем...

**Comment by vas3k** [comment]
Вроде ок
