### ISSUE TITLE
Попробуй всё же пофиксить особые символы в скробблинге

### ISSUE THREAD

**Issue by mutantcornholio** [vas3k/player.vas3k.ru#14]
собственно, скробблится, например, Sleep Party People – I&#39;m Not Human At All, вместо Sleep Party People – I'm Not Human At All. (надеюсь, тут всё проэкранированно, иначе вы увидите одинаковые треки)

**Comment by mutantcornholio** [comment]
конечно, нет! ну там "& #39;"

**Comment by vas3k** [comment]
Сделал принудительную чистку для кавычек.
Оказалось это вконтакте так отдает.
