### ISSUE TITLE
Изчезают точки из названия

### ISSUE THREAD

**Issue by mutantcornholio** [vas3k/player.vas3k.ru#15]
Собственно, делают, сцуки!

**Comment by vas3k** [comment]
Это фича

**Comment by mutantcornholio** [comment]
Блять.. а если я хочу именно группу pg.lost (хотя ластфм в их случае делает автоисправление, слава богу)? Может, такое прикрутить к тому фичреквесту с "точными совпадениями".

**Comment by vas3k** [comment]
Не нужно слушать группы с хуевыми названиеями. А твой фичереквест я не понял.
