### ISSUE TITLE
Реквест: удаление выделенных треков

### ISSUE THREAD

**Issue by mutantcornholio** [vas3k/player.vas3k.ru#16]
Не всегда хочется создавать отдельный плейлист для пары треков и хочется всё, кроме них удалить из выдачи. Хочется выделить всё, убрать нужные треки и УДАЛИТЬ ВЫДЕЛЕННОЕ.

P.S. И вообще, если есть галочки - то удаление выделенных оными галочками треков - вполне предсказуемый юзекйс.

**Comment by vas3k** [comment]
Вопрос куда ставить эту кнопочку? Сверху кнопочки я буду убирать, может быть там будут табы вместо правого сайдбара, может еще чего. Куда их выносить?

**Comment by mutantcornholio** [comment]
Сложно понять, что ты хочешь сделать, так что ещё сложнее сказать, как это дополнить. Нарисуй-сфотай-вышли?

**Comment by vas3k** [comment]
А вот я сам еще не понял как я хочу. Но факт, что хочу избавиться от этих трех кнопочек и добавить твою. Вопрос - как? Куда? Потому что там они явно не в тему.

**Comment by mutantcornholio** [comment]
Согласен. Пусть Артурка скажет, что надо делать :)

**Comment by ReDetection** [comment]
а сверху над списокм треков в том же месте не пойдет?

**Comment by vas3k** [comment]
Ок
