### ISSUE TITLE
по get more не сохраняются фильтры

### ISSUE THREAD

**Issue by ReDetection** [vas3k/player.vas3k.ru#17]
как бы логично, чтобы по get moar сохранялся фильтр по исполнителю/названию и исключались дубли, если это было запрошено в исходном поиске

**Comment by vas3k** [comment]
Давно пора...

**Comment by ReDetection** [comment]
"Удалить дубли" не сохраняется :(
почему-то нет прав на переоткрытие баги. Ваась? :(
