### ISSUE TITLE
Отображение текстов песен. Где лучше сделать?

### ISSUE THREAD

**Issue by vas3k** [vas3k/player.vas3k.ru#19]
На хабре и в твиттере просили прикрутить отображение текстов песен из вконтактика. Как вам было бы удобнее, понятно что кнопка, а куда текст выводить?Думаю сделать табы в правом сайдбаре, есть предложения?

**Comment by Mr-VIT** [comment]
предлагаю сделать так:
правую часть описанием исполнителя убрать
в центральной части сделать табы: текуйщий плейлист (то что сейчас по центру), о текущем исполнителе (то что сейчас справо + расширить информацию)
возле композиции сделать кнопку которая будет окрывать новую вкладку с текстом песни

можно прикрутить поиск текста с http://lyrics.wikia.com/

**Comment by ReDetection** [comment]
предлагаю сайдбар с иполнителем показывать только во время поиска по исполнителю. во время песни - слова песни

**Comment by vas3k** [comment]
Сделал
