### ISSUE TITLE
Плейлист переключается только если ткнуть по тексту

### ISSUE THREAD

**Issue by mutantcornholio** [vas3k/player.vas3k.ru#21]
Плейлист переключается только если ткнуть по тексту. Если ткнуть куда-нибудь рядом, не переключится. Несмотря на то, что полоска выделяется.

**Comment by vas3k** [comment]
Да, известный баг верстки. Переверстаю - поправлю.

**Comment by vas3k** [comment]
В процессе

**Comment by vas3k** [comment]
DONE
