### ISSUE TITLE
Реквест: "Удалить дубликаты" отметить по-умолчанию

### ISSUE THREAD

**Issue by oleksii-zavrazhnyi** [vas3k/player.vas3k.ru#23]

**Comment by mutantcornholio** [comment]
Или в куках сохранять применённые фильтры.

**Comment by ReDetection** [comment]
ща Вася скажет, что надо использовать js storage и что не везде работает.
ну, правильно, куки не для этого, куки вообще передаются на сервер и обрабатываются там

**Comment by vas3k** [comment]
Сделал. Пока что без сохранения с js storage как у звука. Но имею ввиду.
