### ISSUE TITLE
в выдаче обрезаются части строк (служебные слова?)

### ISSUE THREAD

**Issue by ReDetection** [vas3k/player.vas3k.ru#25]
делал поиск по исполнителю hybrid в плеере и в самом вконтакте. во втором случае наименования исполнителя были верными , в плеере же обрезаются последние два символа (id)
например, у трека 10273522_98613765

**Comment by vas3k** [comment]
Не могу повторить.
Не могу представить почему так, никаких манипуляций не делается с названиями.

**Comment by ReDetection** [comment]
сейчас и я не смог повторить, но зуб даю, это было. у меня даже на ластфм статистику cлегка разбавило http://www.lastfm.ru/user/ReDetection/library/music/Hybr

ну, главное, сейчас нет проблемы. закрываю

**Comment by ReDetection** [comment]
во.

http://player.vas3k.ru/#search:hybrid
ищем Hybrid со включенным поиском по исполнителю - все нормально, получаем сначала один-два результата, по get more ‒ много.
без поиска по исполнителю ‒ получаем много обрезанной херни, причем во время такого же запроса вконтакте ‒ те же треки, но названия не обрезаны.

ладно, я бы не переоткрыл эту багу и жил бы с поиском по исполнителю, если бы не одна страшная вещь: если сохранить правильные треки с необрезанными названиями в плейлист и его открыть ‒ они снова обрежутся :(

**Comment by vas3k** [comment]
Ок
