### ISSUE TITLE
выпилить автоисправление из поиска

### ISSUE THREAD

**Issue by ReDetection** [vas3k/player.vas3k.ru#33]
При поиске появляются неверные треки, несмотря на то, что вроде как теперь поиск "точно по исполнителю"

**Шаги воспроизведения:** сделать поиск по исполнителю "the just".
**Обнаружено:** куча треков группы The Dust Brothers :( при этом альбомы отображены верно. при клике на альбом нужные треки появляются, но оооочень медленно

**Comment by vas3k** [comment]
Появится с появлением настроек

**Comment by vas3k** [comment]
Я потестил - без него хуже, просто ищется мусор или пустота. Твоих The Just вконтакте нет видимо. Но на всякий случай выпилил.
