### ISSUE TITLE
Установка на хостинг

### ISSUE THREAD

**Issue by gadzhi** [vas3k/player.vas3k.ru#34]
Подскажите, как установить? куда вбивать настройки?

**Comment by vas3k** [comment]
Хорошо, что написали сюда, можно было и на email правда, а в IM я часто просто забываю.
В плеере используется Pylons, собственно, разворачивается он как любое pylons-приложение (в гугле множество манов, можете выбрать по вкусу, лично я предпочитаю связку uwsgi + nginx).

Вот документация-введение в Pylons: 
http://docs.pylonsproject.org/projects/pylons_framework/dev/gettingstarted.html

А манов по деплойменту реально очень много: 
http://www.google.com/search?client=safari&rls=en&q=pylons&ie=UTF-8&oe=UTF-8#sclient=psy-ab&hl=en&client=safari&rls=en&source=hp&q=pylons+uwsgi+nginx&pbx=1&oq=pylons+uwsgi+n&aq=0&aqi=g1&aql=&gs_sm=e&gs_upl=4318l6298l0l7112l8l6l0l2l2l1l958l1928l0.2.3.6-1l6l0&bav=on.2,or.r_gc.r_pw.r_cp.,cf.osb&fp=bd3772843da9910d&biw=1090&bih=721

**Comment by gadzhi** [comment]
а возможно ли установка на Lamp хостинг или нужен VPS?

**Comment by vas3k** [comment]
Там не нужен ни PHP, ни MySQL, там Python + MongoDB. Возможна установка на любой сервер. Хостинг вряд-ли, но может и повезет.
