### ISSUE TITLE
проблемы со спецсимволами

### ISSUE THREAD

**Issue by ReDetection** [vas3k/player.vas3k.ru#40]
В плейлистах (включая поиски) и сайдбаре спецсимволы подменяются кодами. Сверху в текущем проигрываемом треке все нормально. На last.fm статистика также отправляется кривая.

**Шаги воспроизведения:**  [поискать Hadouken!](http://player.vas3k.ru/#search:hadouken!)
**Получено:** Название исполнителя выводится как `Hadouken&#33;`
**Ожидалось:** Исполнитель выводится везде как `Hadouken!`

**Comment by vas3k** [comment]
Можешь помочь мне найти как преобразовывать & #33; в !

**Comment by ReDetection** [comment]
http://stackoverflow.com/questions/2360598/how-do-i-unescape-html-entities-in-a-string-in-python-3-1

**Comment by vas3k** [comment]
Решено
