### ISSUE TITLE
Удалить дубли в плейлистах

### ISSUE THREAD

**Issue by ReDetection** [vas3k/player.vas3k.ru#45]
При попытке удалить дубли в плейлисте с помощью кнопочки наверху, вкладка в браузере повисает, после выдает пустые диалоги ошибок.
При попытке удалить дубль руками, появляется ошибка
`Проблема с удалением из плейлиста: get() returned more than one PlaylistTracks -- it returned 2! 
Lookup parameters were {'track_id': u'1592265_71051027', 'playlist__id': u'163'}`

**Comment by vas3k** [comment]
Забыл закрыть, но сделал давно.
