### ISSUE TITLE
Возможность добавлять в текущий список

### ISSUE THREAD

**Issue by ReDetection** [vas3k/player.vas3k.ru#46]
нужно добавить возможность в любой момент добавлять выделенные треки в список текущего воспроизведения (фишка в том, что в таком случае не нужно составлять и сохранять какой-нибудь список).

**Comment by vas3k** [comment]
Хорошая штука, я даже изначально планировал. Но сейчас я так запустался с этим NowPlayingList, что даже хз быстро это или нет. Должно быть быстро, если починить один скрытый костыль.

**Comment by vas3k** [comment]
Ну дождались
