### ISSUE TITLE
Надо ли сделать единую авторизацию через вконтакте?

### ISSUE THREAD

**Issue by vas3k** [vas3k/player.vas3k.ru#5]

**Comment by ReDetection** [comment]
это как и чем оно отличается от текущей?

**Comment by vas3k** [comment]
Вчера думал уже. Чето ппц, не знаю как без пересоздания юзеров. Ну короче чтобы не регаться на плеере и вводить логин-пароль сделать просто кнопочку как openid.

**Comment by ReDetection** [comment]
ок, тогда я за

**Comment by mutantcornholio** [comment]
ага. И я.

**Comment by ReDetection** [comment]
слева сверху кнопочка vote, нажми ее. голосование.

**Comment by oleksii-zavrazhnyi** [comment]
Однозначно. И все лайки отправлять на стену вконтакте.

**Comment by ReDetection** [comment]
Для лайков лучше отдельный реквест. И вообще, кажется, потихоньку зреет необходимость в странице настроек плеера. Потому что мне, например, не нужно отправлять лайки на стену

**Comment by vas3k** [comment]
Да, такие фичи без настроек я делать не буду. В следующей версии попробую предусмотреть настройки.

**Comment by oleksii-zavrazhnyi** [comment]
Да, настройки надо

**Comment by vas3k** [comment]
Пока отложено...

**Comment by ReDetection** [comment]
отложил так отложил, но зачем закрыл-то?
задай milestone на него чонить типа "future"  и все
