### ISSUE TITLE
Галочки наоборот.

### ISSUE THREAD

**Issue by mutantcornholio** [vas3k/player.vas3k.ru#7]
продолжая тему кривоватости интерфейса.
возможно такое: http://dl.dropbox.com/u/1880889/51.png

**Comment by vas3k** [comment]
Не удалось воспроизвести

**Comment by mutantcornholio** [comment]
Ок, сейчас попытаюсь.

**Comment by mutantcornholio** [comment]
нажимаешь на галочку. Тыкаешь чёнить из меню слева. Снова нажимаешь на галочку.

**Comment by vas3k** [comment]
Ок
