### ISSUE TITLE
Точные совпадения.

### ISSUE THREAD

**Issue by mutantcornholio** [vas3k/player.vas3k.ru#8]
Хочу синтаксис, вроде "artist or song" и в выдаче не будет элементов вроде
65 artist or song - shit
(post-rock) artist or song - shit 

blabla - SHIT!!! FUCKIN LISTEN THIS artist or song
Ну а потом можно отфильтровать, по исполнителю или песне.

**Comment by vas3k** [comment]
Не понял. Пример.

**Comment by mutantcornholio** [comment]
http://dl.getdropbox.com/u/1880889/2011-02-11-130909_1920x1080_scrot.png

**Comment by mutantcornholio** [comment]
shit. нажал "Comment and Close" =\

**Comment by mutantcornholio** [comment]
Может, перенесёшь в open?
